# Generated by Django 3.1.7 on 2021-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210403_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[['single', 'Single'], ['married', 'Marride']], default='single', max_length=100),
        ),
    ]
