# Generated by Django 3.1.7 on 2021-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210403_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[['single', 'Single'], ['married', 'Married']], default='single', max_length=100),
        ),
    ]
