# Generated by Django 3.1.7 on 2021-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210403_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[['male', 'Male'], ['female', 'Female']], default='male', max_length=100),
        ),
    ]
