# Generated by Django 3.1.7 on 2021-04-03 10:55

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[['male', 'Male'], ['female', 'Female']], default='male', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='IDR', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[['single', 'Single'], ['married', 'Married']], default='single', max_length=100, null=True),
        ),
    ]
