# Generated by Django 3.1.7 on 2021-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210403_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[['Male', 'Male'], ['Female', 'Female']], default='male', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[['Single', 'Single'], ['Married', 'Married']], default='single', max_length=100, null=True),
        ),
    ]
