# Generated by Django 3.1.7 on 2021-04-03 12:19

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210403_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='IDR', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=100),
        ),
    ]
