# Generated by Django 3.1.7 on 2021-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210403_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='income_int',
            field=models.IntegerField(null=True),
        ),
    ]
