# Generated by Django 3.1.7 on 2021-04-05 00:59

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_income_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='IDR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income_int',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
