# Generated by Django 3.1.7 on 2021-04-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20210405_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='income_currency',
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=models.CharField(max_length=100),
        ),
    ]
